build-deploy documentation
equinor/radix-public-site pull request #273
Opened 2023-11-09 15:41 UTC by nilsgstrabo

2023-11-10 13:34 UTC, emirgens reviewed
Too much text for me to understand, but see my comment in text

2023-11-10 14:16 UTC, nilsgstrabo commented on public-site/docs/src/guides/build-and-deploy/index.md
> +- When `build secret` values are updated, the next pipeline job will build all components and jobs.
fixed

2023-11-10 14:29 UTC, satr commented on public-site/docs/src/guides/build-and-deploy/index.md
> +For manually created pipeline jobs, Radix will always build all components and jobs. When a pipeline job is created from a Github webhook, Radix compares the commit ID from the webhook request body w
```suggestion
For manually created pipeline jobs, Radix will always build all components and jobs without defined property `image`. When a pipeline job is created by a Github webhook, Radix compares the commit ID from the webhook request body with the commit ID of the active deployment to detect which directories have changed. The list of changed directories are then compared to the `src` property for each component and job:
* If any of the changed directories are within  the directory, defined in `src` or are its sub-directories, a new image is built for the component and job. 
* if no such changes detected, Radix will reuse the image from the current active deployment for components and jobs.
```

2023-11-13 09:20 UTC, nilsgstrabo commented on public-site/docs/src/guides/build-and-deploy/index.md
> +For manually created pipeline jobs, Radix will always build all components and jobs. When a pipeline job is created from a Github webhook, Radix compares the commit ID from the webhook request body w
This is described in the previous paragraph. I don't think there is a need to describe it one more time.

2023-11-13 09:21 UTC, Richard87 requested changes
Looks good, tiny comment on word splitting (Dockerfiles)

2023-11-13 09:21 UTC, Richard87 commented on public-site/docs/src/guides/build-and-deploy/index.md
> +Components `foo` and `bar` are configured with different directories for their Docker files. We assume that an active deployment already exist, created from a `build-deploy` pipeline that built and d
remove space, "Docker files" => "Dockerfiles"?

2023-11-13 09:21 UTC, Richard87 commented on public-site/docs/src/guides/build-and-deploy/index.md
> +The [`build-deploy`](../../start/workflows/) pipeline builds and deploys container images from Docker files for components and jobs that do not have the [`image`](../../references/reference-radix-con
Change `Docker files` to `Dockerfiles`?

2023-11-13 09:25 UTC, nilsgstrabo commented on public-site/docs/src/guides/build-and-deploy/index.md
> +The [`build-deploy`](../../start/workflows/) pipeline builds and deploys container images from Docker files for components and jobs that do not have the [`image`](../../references/reference-radix-con
fixed

2023-11-13 09:28 UTC, Richard87 submitted a review, later dismissed
lgtm!

2023-11-13 13:06 UTC, satr submitted a review, later dismissed

2023-11-13 15:02 UTC, satr approved these changes

2023-11-13 15:09 UTC, merged