Add Dynatrace information
equinor/radix-public-site pull request #287
Opened 2023-11-30 09:46 UTC by Richard87

Requires https://github.com/equinor/radix/issues/115

2023-12-08 09:56 UTC, satr reviewed
Use of internal links needs to be approved by PO

2023-12-11 08:54 UTC, emirgens requested changes
Now I see the issue, these links will work without the token. Then the access is "protected"

2023-12-11 08:54 UTC, emirgens commented on public-site/docs/src/docs/topic-dynatrace-int/index.md
> +- Read about Dynatrace Container monitoring integration [here](https://statoilsrm.sharepoint.com/sites/applicationperformancemanagement/SitePages/Container-monitoring---attaching-to-a-management-zone
```suggestion
- Read about Dynatrace Container monitoring integration [here](https://statoilsrm.sharepoint.com/sites/applicationperformancemanagement/SitePages/Container-monitoring---attaching-to-a-management-zone.aspx)
```

2023-12-11 08:54 UTC, emirgens commented on public-site/docs/src/docs/topic-dynatrace-int/index.md
> +- Read about Dynatrace secrets and configuration [here](https://statoilsrm.sharepoint.com/sites/applicationperformancemanagement/SitePages/Install-on-Linux.aspx?xsdata=MDV8MDF8fDRlMTgyMmRkYTU3YjRmOWV
```suggestion
- Read about Dynatrace secrets and configuration [here](https://statoilsrm.sharepoint.com/sites/applicationperformancemanagement/SitePages/Install-on-Linux.aspx)
```

2023-12-11 12:43 UTC, emirgens approved these changes
ok

2023-12-11 12:50 UTC, merged