docs-about-sub-pipeline-vars-and-identity
equinor/radix-public-site pull request #350
Opened 2024-04-29 12:36 UTC by satr

## What type of PR? (can choose many)
- [ ] 🍕 Added/Updated documentation
- [ ] 🎨 Style
- [ ] 🔒 Security

## Description

2024-04-29 16:29 UTC, Richard87 reviewed
I still think its a bit confusing, can we start with a section with the simplest possible configuration?

2024-04-29 16:37 UTC, Richard87 requested changes
I still think its a bit confusing, can we start with a section with the simplest possible configuration?

2024-04-29 16:37 UTC, Richard87 commented on public-site/docs/radix-config/index.md
> +`variables` - (optional, available only in [sub-pipelines](/guides/sub-pipeline), they are ignored for sub-pipeline if the [subPipeline](/radix-config/index.md#subpipeline) option exists) environment
I'm not sure what this means?

1. If any sub-pipeline environment variables are set, all _regular_ variables are discarded?
2. Any sub-pipeline environment variables will merge, and override _regular_ variables?

Will regular build secrets and variables be available?

2024-04-30 06:23 UTC, satr commented on public-site/docs/radix-config/index.md
> +`variables` - (optional, available only in [sub-pipelines](/guides/sub-pipeline), they are ignored for sub-pipeline if the [subPipeline](/radix-config/index.md#subpipeline) option exists) environment
1. Yes 
2. Yes
3. Regular build secrets [are available](https://www.radix.equinor.com/guides/sub-pipeline/example-pipeline-with-build-secrets) with `$(radix.build-secrets)`, env vars as described, but it is good point - I'll fix env-vars examples.

2024-04-30 06:44 UTC, satr commented on public-site/docs/radix-config/index.md
> +`variables` - (optional, available only in [sub-pipelines](/guides/sub-pipeline), they are ignored for sub-pipeline if the [subPipeline](/radix-config/index.md#subpipeline) option exists) environment
Fixed

2024-05-02 09:04 UTC, Richard87 approved these changes
Godkjent

2024-05-02 09:06 UTC, merged